version: '3.8'

services:
  database:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    container_name: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: single-service-api
    restart: on-failure
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - database
    volumes:
      - ./src:/app/src